//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Interfaces {    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources
    {

        private static string resourceSettings = "Settings.ini";

        private static string resourceNewline = "\n";

        private static string resDatabase = "DatabaseFormat";
        private static string resTheme = "Theme";
        private static string resAccent = "Accent";
        private static string resSectionDatabase = "Database";
        private static string resSectionAppearence = "Aussehen";
        private static string resStandardDBPath = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile) + @"\Local Settings\Verwaltung\";
        private static string resDatabasePath = "DBPath";
        private static string resDataBaseFile = "DBFile";
        private static string resSectionAPIKey = "API-Key";
        private static string resAPIKey = "ApiKey";
        private static string resView = "View";

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        public static string View
        {
            get
            {
                return resView;
            }
        }

        public static string ApiKey
        {
            get
            {
                return resAPIKey;
            }
        }

        public static string SectionAPIKey
        {
            get
            {
                return resSectionAPIKey;
            }
        }

        public static string DatabaseFile
        {
            get
            {
                return resDataBaseFile;
            }
        }

        public static string DatabasePath
        {
            get
            {
                return resDatabasePath;
            }
        }

        public static string StandardDBPath
        {
            get
            {
                return resStandardDBPath;
            }
        }

        public static string SectionDatabase
        {
            get
            {
                return resSectionDatabase;
            }
        }

        public static string Database
        {
            get
            {
                return resDatabase;
            }
        }

        public static string SettingIni
        {
            get
            {
                return resourceSettings;
            }
        }

        public static string SectionAppearence
        {
            get
            {
                return resSectionAppearence;
            }
        }

        public static string Theme
        {
            get
            {
                return resTheme;
            }
        }

        public static string Accent
        {
            get
            {
                return resAccent;
            }
        }

        public static string NewLine
        {
            get
            {
                return resourceNewline;
            }
        }



        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
